ROM_WIDTH = 8
ROM_GRP1  = ROM_WIDTH*0
ROM_GRP2  = ROM_WIDTH*1
ROM_GRP3  = ROM_WIDTH*2
ROM_GRP4  = ROM_WIDTH*3
ROM_GRP5  = ROM_WIDTH*4

ROM_POS0  = 0
ROM_POS1  = 1
ROM_POS2  = 2
ROM_POS3  = 3
ROM_POS4  = 4
ROM_POS5  = 5
ROM_POS6  = 6
ROM_POS7  = 7


AAC	    =   1   <<      (ROM_GRP2 + ROM_POS4)
ACO	    =   1   <<      (ROM_GRP4 + ROM_POS0)
ACU	    =   1   <<      (ROM_GRP2 + ROM_POS7)
AIB	    =   1   <<      (ROM_GRP4 + ROM_POS2)
ARI	    =   1   <<      (ROM_GRP4 + ROM_POS1)
ARO	    =   1   <<      (ROM_GRP4 + ROM_POS7)
ASI	    =   1   <<      (ROM_GRP2 + ROM_POS5)
ASO	    =   1   <<      (ROM_GRP4 + ROM_POS4)
ASX	    =   1   <<      (ROM_GRP4 + ROM_POS3)
AUA	    =   1   <<      (ROM_GRP4 + ROM_POS6)
AUN	    =   1   <<      (ROM_GRP4 + ROM_POS5)
CCU	    =   1   <<      (ROM_GRP2 + ROM_POS6)
GAO	    =   1   <<      (ROM_GRP1 + ROM_POS4)
GBO	    =   1   <<      (ROM_GRP1 + ROM_POS3)
HT	    =   1   <<      (ROM_GRP5 + ROM_POS4)
IHI	    =   1   <<      (ROM_GRP1 + ROM_POS2)
ILI	    =   1   <<      (ROM_GRP1 + ROM_POS1)
MAHI	=   1   <<      (ROM_GRP3 + ROM_POS1)
MALI	=   1   <<      (ROM_GRP3 + ROM_POS0)
MI	    =   1   <<      (ROM_GRP3 + ROM_POS2)
MO	    =   1   <<      (ROM_GRP1 + ROM_POS0)
MRH	    =   1   <<      (ROM_GRP3 + ROM_POS3)
NI	    =   1   <<      (ROM_GRP1 + ROM_POS7)
PHI	    =   1   <<      (ROM_GRP5 + ROM_POS2)
PHO	    =   1   <<      (ROM_GRP2 + ROM_POS1)
PI	    =   1   <<      (ROM_GRP3 + ROM_POS4)
PLI	    =   1   <<      (ROM_GRP5 + ROM_POS3)
PLO	    =   1   <<      (ROM_GRP2 + ROM_POS0)
RAS	    =   1   <<      (ROM_GRP1 + ROM_POS6)
RBS	    =   1   <<      (ROM_GRP1 + ROM_POS5)
RI	    =   1   <<      (ROM_GRP5 + ROM_POS7)
RO	    =   1   <<      (ROM_GRP5 + ROM_POS6)
RS0	    =   1   <<      (ROM_GRP5 + ROM_POS5)
SD	    =   1   <<      (ROM_GRP3 + ROM_POS5)
SHI	    =   1   <<      (ROM_GRP5 + ROM_POS0)
SHO	    =   1   <<      (ROM_GRP2 + ROM_POS2)
SI	    =   1   <<      (ROM_GRP3 + ROM_POS6)
SLI	    =   1   <<      (ROM_GRP5 + ROM_POS1)
SLO	    =   1   <<      (ROM_GRP2 + ROM_POS3)

NOINST  =   0