ROM_WIDTH = 8
ROM_GRP1  = ROM_WIDTH*0
ROM_GRP2  = ROM_WIDTH*1
ROM_GRP3  = ROM_WIDTH*2
ROM_GRP4  = ROM_WIDTH*3
ROM_GRP5  = ROM_WIDTH*4

ROM_POS0  = 0
ROM_POS1  = 1
ROM_POS2  = 2
ROM_POS3  = 3
ROM_POS4  = 4
ROM_POS5  = 5
ROM_POS6  = 6
ROM_POS7  = 7


AAC	    =   1   <<      (ROM_GRP2 + 0)
ACO	    =   1   <<      (ROM_GRP4 + ROM_POS0)
ACU	    =   1   <<      (ROM_GRP2 + 0)
AIB	    =   1   <<      (ROM_GRP4 + ROM_POS2)
ARI	    =   1   <<      (ROM_GRP4 + ROM_POS1)
ARO	    =   1   <<      (ROM_GRP4 + ROM_POS7)
ASI	    =   1   <<      (ROM_GRP2 + 0)
ASO	    =   1   <<      (ROM_GRP4 + ROM_POS4)
ASX	    =   1   <<      (ROM_GRP4 + ROM_POS3)
AUA	    =   1   <<      (ROM_GRP4 + ROM_POS6)
AUN	    =   1   <<      (ROM_GRP4 + ROM_POS5)
CC	    =   1   <<      (ROM_GRP2 + 0)
GAO	    =   1   <<      (ROM_GRP1 + 0)
GBO	    =   1   <<      (ROM_GRP1 + 0)
HT	    =   1   <<      (ROM_GRP5 + 0)
IHI	    =   1   <<      (ROM_GRP1 + 0)
ILI	    =   1   <<      (ROM_GRP1 + 0)
MAHI	=   1   <<      (ROM_GRP3 + 0)
MALI	=   1   <<      (ROM_GRP3 + 0)
MI	    =   1   <<      (ROM_GRP3 + 0)
MO	    =   1   <<      (ROM_GRP1 + 0)
MRH	    =   1   <<      (ROM_GRP3 + 0)
NI	    =   1   <<      (ROM_GRP1 + 0)
PHI	    =   1   <<      (ROM_GRP3 + 0)
PHO	    =   1   <<      (ROM_GRP5 + 0)
PI	    =   1   <<      (ROM_GRP3 + 0)
PLI	    =   1   <<      (ROM_GRP3 + 0)
PLO	    =   1   <<      (ROM_GRP5 + 0)
RAS	    =   1   <<      (ROM_GRP1 + 0)
RBS	    =   1   <<      (ROM_GRP1 + 0)
RI	    =   1   <<      (ROM_GRP5 + 0)
RO	    =   1   <<      (ROM_GRP5 + 0)
RS0	    =   1   <<      (ROM_GRP5 + 0)
SD	    =   1   <<      (ROM_GRP2 + 0)
SHI	    =   1   <<      (ROM_GRP2 + 0)
SHO	    =   1   <<      (ROM_GRP5 + 0)
SI	    =   1   <<      (ROM_GRP2 + 0)
SLI	    =   1   <<      (ROM_GRP2 + 0)
SLO	    =   1   <<      (ROM_GRP5 + 0)

NOINST  =   0